name: Frontend CI/CD Docker Deploy to EC2

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push front-service
        run: |
          echo "NEXT_PUBLIC_TOSS_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_TOSS_CLIENT_KEY }}" >> ./apps/user/.env.production

          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> ./apps/user/.env.production
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> ./apps/user/.env.production
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}" >> ./apps/user/.env.production
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}" >> ./apps/user/.env.production
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}" >> ./apps/user/.env.production
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID}}" >> ./apps/user/.env.production
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}}" >> ./apps/user/.env.production
          echo "NEXT_PUBLIC_FIREBASE_VAPID_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY}}" >> ./apps/user/.env.production

          echo "NEXT_PUBLIC_BASE_API_URL=${{NEXT_PUBLIC_BASE_API_URL}}" >> ./apps/user/.env.production
          echo "NEXT_PUBLIC_WEBSOCKET_DOMAIN=${{NEXT_PUBLIC_WEBSOCKET_DOMAIN}}" >> ./apps/user/.env.production

          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> ./apps/busker/.env.production
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> ./apps/busker/.env.production
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}" >> ./apps/busker/.env.production
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}" >> ./apps/busker/.env.production
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}" >> ./apps/busker/.env.production
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID}}" >> ./apps/busker/.env.production
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}}" >> ./apps/busker/.env.production
          echo "NEXT_PUBLIC_FIREBASE_VAPID_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY}}" >> ./apps/busker/.env.production

          echo "NEXT_PUBLIC_BASE_API_URL=${{NEXT_PUBLIC_BASE_API_URL}}" >> ./apps/busker/.env.production
          echo "NEXT_PUBLIC_WEBSOCKET_DOMAIN=${{NEXT_PUBLIC_WEBSOCKET_DOMAIN}}" >> ./apps/busker/.env.production

          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/front-service:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/front-service:${{ github.sha }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/vybz/front-service

            echo "[1] .env.user ìƒì„±"
            echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" > .env.user
            echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.user
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.user
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.user
            echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env.user
            echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env.user
            echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env.user
            echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> .env.user
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env.user
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env.user
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env.user
            echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env.user
            echo "NEXT_PUBLIC_TOSS_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_TOSS_CLIENT_KEY }}" >> .env.user
            echo "TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}" >> .env.user

            echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env.user
            echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env.user
            echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env.user
            echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env.user
            echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> .env.user
            echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env.user
            echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" >> .env.user
            echo "NEXT_PUBLIC_FIREBASE_VAPID_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY }}" >> .env.user

            echo "NEXT_PUBLIC_BASE_API_URL=${{NEXT_PUBLIC_BASE_API_URL}}" >> .env.user
            echo "NEXT_PUBLIC_WEBSOCKET_DOMAIN=${{NEXT_PUBLIC_WEBSOCKET_DOMAIN}}" >> .env.user

            echo "[2] .env.busker ìƒì„±"
            echo "NEXTAUTH_URL=${{ secrets.BUSKER_NEXTAUTH_URL }}" > .env.busker
            echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.busker
            echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env.busker
            echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> .env.busker
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env.busker
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env.busker
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env.busker
            echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env.busker

            echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env.busker
            echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env.busker
            echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env.busker
            echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env.busker
            echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> .env.busker
            echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env.busker
            echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" >> .env.busker
            echo "NEXT_PUBLIC_FIREBASE_VAPID_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY }}" >> .env.busker

            echo "NEXT_PUBLIC_BASE_API_URL=${{NEXT_PUBLIC_BASE_API_URL}}" >> .env.busker
            echo "NEXT_PUBLIC_WEBSOCKET_DOMAIN=${{NEXT_PUBLIC_WEBSOCKET_DOMAIN}}" >> .env.busker

            echo "[3] ì»¨í…Œì´ë„ˆ ì •ë¦¬"
            docker-compose down
            docker-compose rm -f

            echo "[4] ì´ë¯¸ì§€ ì •ë¦¬"
            docker images "${{ secrets.DOCKER_HUB_USERNAME }}/front-service" --format "{{.ID}}" | uniq | tail -n +2 | xargs -r docker rmi -f
            docker image prune -af

            echo "[5] ì¬ì‹œì‘"
            export FRONT_IMAGE_TAG=${{ github.sha }}
            docker-compose pull
            docker-compose up -d front-user
            docker-compose up -d front-busker
            docker-compose up -d front-admin

      - name: Send Discord Success Notification
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_FRONT }}
        with:
          args: |
            âœ… [${{ github.actor }}]ë‹˜ì´ `${{ github.repository }}` ë ˆí¬ì§€í† ë¦¬ì—ì„œ **ë°°í¬ë¥¼ ì™„ë£Œ**í–ˆì–´ìš”!
            ğŸ”— ì»¤ë°‹: ${{ github.sha }}

      - name: Send Discord Failure Notification
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_FRONT }}
        with:
          args: |
            âŒ [${{ github.actor }}]ë‹˜ì´ `${{ github.repository }}` ë ˆí¬ì§€í† ë¦¬ì—ì„œ **ë°°í¬ì— ì‹¤íŒ¨**í–ˆì–´ìš”!
            ğŸ” ì—ëŸ¬ ë¡œê·¸ë¥¼ í™•ì¸í•´ì£¼ì„¸ìš”.